version: "3"
services:

  hms-sdk-widget:
    container_name: hms-sdk-widget
    environment: 
      - DCP_PORT=8881
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - ./app/.env.production
    ports:
      - "8881:8881"
    expose:
      - 8881
    volumes:
      - ./app:/app/hms-sdk-widget
      - /app/hms-sdk-widget/node_modules  # [*] Need to refer to node_modules in container of the app
    entrypoint:
      - sh
      - entrypoint-prod.sh
    restart: always

networks:
  default:
    external:
      name: iassdk